project/route/routes.py
from flask import Blueprint, render_template, redirect, request, url_for
from .way import Way
from markupsafe import escape
from .exception import Roads_exception

# Defining a blueprint
way_bp = Blueprint(
    'way_bp', __name__,
    template_folder='templates'
)

@way_bp.route('/insert', methods=['POST'])
def insert():
    try:
        route = Way.get_route_nationale(request.form['route'])
        route.set_point_kilometrique(request.form['depart'], request.form['arrive'])
        route.set_niveau(request.form['niveau'])
        route.insert()
        return render_template('formulaire.html', page = "insert", route = None)
    except Roads_exception as e:
        points = ""
        for road in e.get_ways():
            points += str(road.get_depart()) + " et " + str(road.get_arrive()) + "<br>"
        return render_template('formulaire.html', error = str(e) + "<br>" + points, page = "insert", route = None)
    except Exception as e:
        return render_template('formulaire.html', error = e, page = "insert", route = None)


@way_bp.route('/liste', methods=['POST'])
def show():
    route = Way.get_route_nationale(request.form['route'])
    try:
        route.set_point_kilometrique(request.form['depart'], request.form['arrive'])
        return render_template('formulaire.html', route = route, page = "show")
    except Exception as e:
        return render_template('formulaire.html', route = None, error = e, page = "show")


@way_bp.route('/formulaire')
def formulaire():
    return render_template('formulaire.html', page = request.args.get('page'), route = None)

project/route/templates/formulaire.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/assets/css/bootstrap.css">
    <title>{{ page }}</title>
</head>
<style>
    #map {
        border-radius: 20px;
        width: 675px; 
        height: 300px;
    }
</style>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAtBfUgArg9M-eu4m9ilh1G3n1hwyTozJw&callback=initMap"></script>
<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -18.419, lng: 47.24},
            zoom: 10
        });

        var marker1 = new google.maps.Marker({
            position: {lat: -18.419, lng: 47.24},
            map: map
        });

        var marker2 = new google.maps.Marker({
            position: {lat: -18.90, lng: 47.24},
            map: map
        });

        var directionsService = new google.maps.DirectionsService();
        var directionsRenderer = new google.maps.DirectionsRenderer();

        var request = {
            origin: marker1.getPosition(),
            destination: marker2.getPosition(),
            travelMode: 'DRIVING'
        };

        directionsService.route(request, function(result, status) {
            if (status == 'OK') {
                directionsRenderer.setDirections(result);
            }
        });

        directionsRenderer.setMap(map);
    }
  </script>
<body onload="initMap()">
    <div class="shadow-sm p-4 container rounded-3 mt-4 w-50">
        <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link text-dark" href="{{ url_for('way_bp.formulaire') + '?page=show' }}">Prix</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{{ url_for('way_bp.formulaire') + '?page=insert' }}">Ajouter</a>
            </li>
        </ul>
    </div>
    {% if page != "insert":%}
    <div class="container mt-5">
        <div id="map" class="mx-auto shadow"></div>
    </div>
    {% endif %}
    <div class="container w-50 shadow p-5 rounded-3 my-5">
        <form action="{{ url_for('way_bp.' + page) }}" method="post">
            <div class="row mb-4">
                <select name="route" class="form-select mx-auto" style="width: 587px;">
                    <option value="RNP 2">RNP 2</option>
                    <option value="RNP 7">RNP 7</option>
                    <option value="RNP 4">RNP 4</option>
                </select>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <input type="text" placeholder="Debut" name="depart" class="form-control">
                </div>
                <div class="col">
                    <input type="text" placeholder="Arrive" name="arrive" class="form-control">
                </div>
            </div>
            {% if page == "insert":%}
                <input type="text" placeholder="Niveau" name="niveau" class="form-control">
            {% endif %}
            <div class="container mt-4 mb-3">
                <button class="btn btn-dark px-5" style="margin-left: 210px;">{{ page }}</button>
            </div>
            {% if error != None:%}
                <h1>{{ error | safe }}</h1>
            {% endif %}
        </form>
        {% if route != None:%}
            <div>
                <h3>Prix: {{ route.get_prix_reparation() }} Ariary</h3>
                <h3>Duree: {{ route.get_duree_reparation() }}</h3>
            </div>
        {% endif %}
    </div>
</body>
</html>